"""Markdown reporter for human-readable evaluation reports."""

from pathlib import Path
from typing import List
from ...domain.contracts import Reporter
from ...domain.entities import RunSummary, ReportSpec


class MarkdownReporter:
    """Reporter that generates Markdown output for human consumption."""
    
    def render(self, run_summary: RunSummary, report_spec: ReportSpec) -> None:
        """Generate Markdown report from run summary."""
        
        # Generate report content
        content_lines = self._generate_content(run_summary, report_spec)
        
        # Write to file
        output_path = Path(report_spec.output_dir) / "summary.md"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(content_lines))
    
    def _generate_content(self, run_summary: RunSummary, report_spec: ReportSpec) -> List[str]:
        """Generate markdown content lines."""
        lines = []
        
        # Header
        lines.extend([
            "# ValtaPyV2 Evaluation Report",
            "",
            f"**Generated by:** ValtaPyV2 v0.1.0",
            "",
        ])
        
        # Executive Summary
        lines.extend([
            "## Executive Summary",
            "",
            f"- **Total Metrics:** {len(run_summary.results)}",
            f"- **Successful:** {len([r for r in run_summary.results if 'error' not in r.details])}",
            f"- **Failed:** {len([r for r in run_summary.results if 'error' in r.details])}",
            ""
        ])
        
        # Overall Scores
        if "composite_score" in run_summary.aggregates:
            lines.extend([
                f"- **Composite Score:** {run_summary.aggregates['composite_score']:.3f}",
                ""
            ])
        
        # Evaluation Plan
        lines.extend([
            "## Evaluation Configuration",
            "",
            f"- **Purpose:** {run_summary.plan.purpose or 'Not specified'}",
            f"- **Random Seed:** {run_summary.plan.seed}",
            f"- **CV Splits:** {run_summary.plan.cv_splits}",
            f"- **Metrics:** {len(run_summary.plan.metric_ids)}",
            ""
        ])
        
        # Family Scores
        lines.extend([
            "## Family Scores",
            "",
            "| Family | Score | Count |",
            "|--------|-------|-------|"
        ])
        
        for family in ["fidelity", "utility", "privacy"]:
            score = run_summary.aggregates.get(f"{family}_score", 0.0)
            family_results = run_summary.get_results_by_family(family)
            count = len(family_results)
            lines.append(f"| {family.title()} | {score:.3f} | {count} |")
        
        lines.append("")
        
        # Detailed Results
        lines.extend([
            "## Detailed Results",
            "",
            "| Metric ID | Family | Value | Status |",
            "|-----------|--------|--------|--------|"
        ])
        
        for result in sorted(run_summary.results, key=lambda x: (x.family, x.id)):
            status = "✅ Success" if "error" not in result.details else "❌ Failed"
            value_str = f"{result.value:.4f}" if "error" not in result.details else "N/A"
            lines.append(f"| `{result.id}` | {result.family} | {value_str} | {status} |")
        
        lines.append("")
        
        # Family Details
        for family in ["fidelity", "utility", "privacy"]:
            family_results = run_summary.get_results_by_family(family)
            if not family_results:
                continue
                
            lines.extend([
                f"### {family.title()} Metrics",
                ""
            ])
            
            for result in family_results:
                lines.extend([
                    f"#### {result.id}",
                    ""
                ])
                
                if "error" in result.details:
                    lines.extend([
                        f"**Status:** ❌ Failed",
                        f"**Error:** {result.details['error']}",
                        ""
                    ])
                else:
                    lines.extend([
                        f"**Value:** {result.value:.4f}",
                        f"**Status:** ✅ Success",
                        ""
                    ])
                    
                    if report_spec.include_details and result.details:
                        lines.extend([
                            "**Details:**",
                            ""
                        ])
                        
                        for key, value in result.details.items():
                            if key != "error":
                                if isinstance(value, (int, float)):
                                    lines.append(f"- **{key}:** {value}")
                                elif isinstance(value, (list, dict)) and len(str(value)) < 100:
                                    lines.append(f"- **{key}:** {value}")
                                else:
                                    lines.append(f"- **{key}:** {type(value).__name__}")
                        
                        lines.append("")
        
        # Aggregation Details
        if run_summary.aggregates:
            lines.extend([
                "## Aggregation Details",
                ""
            ])
            
            for key, value in run_summary.aggregates.items():
                if isinstance(value, (int, float)):
                    lines.append(f"- **{key}:** {value:.4f}")
                else:
                    lines.append(f"- **{key}:** {value}")
            
            lines.append("")
        
        # Warnings and Issues
        if run_summary.artifacts.get("warnings"):
            lines.extend([
                "## Warnings",
                ""
            ])
            
            for warning in run_summary.artifacts["warnings"]:
                lines.append(f"⚠️ {warning}")
            
            lines.append("")
        
        # Footer
        lines.extend([
            "---",
            "",
            "*Report generated by ValtaPyV2*"
        ])
        
        return lines